// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1u6qzyvLsGpChf180iFURLdFt3wpaLv8',
    appId: '1:174635148214:web:78405067d647121e5f1717',
    messagingSenderId: '174635148214',
    projectId: 'project1-af690',
    authDomain: 'project1-af690.firebaseapp.com',
    storageBucket: 'project1-af690.appspot.com',
    measurementId: 'G-V6N7ZQ4QBS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBou5afIi1q3AKg02Ds86BqF5WfYbMutVk',
    appId: '1:174635148214:android:ee007c4f3426b8445f1717',
    messagingSenderId: '174635148214',
    projectId: 'project1-af690',
    storageBucket: 'project1-af690.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUEMooSTdgQbr8IolEp76jJgruv7b5-Mg',
    appId: '1:174635148214:ios:26225c593e106b635f1717',
    messagingSenderId: '174635148214',
    projectId: 'project1-af690',
    storageBucket: 'project1-af690.appspot.com',
    iosClientId: '174635148214-ntjj20nsvrigo34cdgmk1ovfr8np30p1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUEMooSTdgQbr8IolEp76jJgruv7b5-Mg',
    appId: '1:174635148214:ios:6eda2e1bf7a0eaf75f1717',
    messagingSenderId: '174635148214',
    projectId: 'project1-af690',
    storageBucket: 'project1-af690.appspot.com',
    iosClientId: '174635148214-b5gcjh5npi4h6grsbqhgl87rkjcnjaid.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
